### ISSUE TITLE
Recommender

### ISSUE THREAD

**Issue by gsingers** [lucidworks/searchhub#22]
Add a backend recommender module to searchhub, starting with a moreLikeThis based on content as well as co-authorship on a thread.

**Comment by gsingers** [comment]
Summarizing the plan @jakemannix:
1. I'll work on MLT and UI
2. You work on basic co-occurrence based recommender for user aliases (e.g. taking the from user out of an email and showing them recommended other emails)
3. I'll work on UI for per document view.

**Comment by jakemannix** [comment]
Looks like all 3 of these are taken care of now, on https://github.com/lucidworks/searchhub/tree/GH-28-doc-view

**Comment by gsingers** [comment]
This is merged to Master
