### ISSUE TITLE
Add datasources for Lucidworks videos (webinars, et. al) and Lucene/Solr videos

### ISSUE THREAD

**Issue by gsingers** [lucidworks/searchhub#31]
Setup crawlers for:
1. https://www.youtube.com/user/LucidWorksSearch
2. https://vimeo.com/user11514798

**Comment by gsingers** [comment]
We can ignore the Vimeo one, there isn't much content there.

**Comment by lasyamarla** [comment]
Added the youtube crawler to the python/project_config/lucidworks.json file

**Comment by lasyamarla** [comment]
https://github.com/lucidworks/searchhub/tree/GH-31-youtube_parser
