### ISSUE TITLE
Using filters generates "There are no results" message (with HTTP 400 error in JSON)

### ISSUE THREAD

**Issue by arafalov** [lucidworks/searchhub#58]
I did an ego search (Rafalovitch) and then tried using various filters. Selecting more than one author triggers the error. So it seems a single date range. The sample queries are below:

> http://searchhub.lucidworks.com/api/apollo/collections/lucidfind/query-profiles/default/select?q=rafalovitch&start=0&wt=json&rows=10&uuid=7cb61ab9-6cde-4b1a-8ea1-2b98ebf2d4f3&fq=isBot:(%22true%22)&fq={!tag=auth}author_facet:(%22Alexandre%20Rafalovitch%20(JIRA%20OR%20%22arafalov%22)&sort=publishedOnDate%20desc
> 
> http://searchhub.lucidworks.com/api/apollo/collections/lucidfind/query-profiles/default/select?q=Rafalovitch&start=0&wt=json&rows=10&uuid=35fb5f56-7f0b-4c51-b3a5-31990a6da985&fq={!tag=auth}author_facet:(%22Alexandre%20Rafalovitch%20(JIRA%20OR%20%22Jack%20Krupansky%22)
> 
> http://searchhub.lucidworks.com/api/apollo/collections/lucidfind/query-profiles/default/select?q=Rafalovitch&start=0&wt=json&rows=10&uuid=e49e54a5-2995-4a3b-b16f-ca222ff6b812&fq=publishedOnDate:[Feb+29%2C+2016+TO+Mar+29%2C+2016]
> 
> http://searchhub.lucidworks.com/api/apollo/collections/lucidfind/query-profiles/default/select?q=Rafalovitch&start=0&wt=json&rows=10&uuid=dd214c69-58ed-4ebe-9655-2394954093b1&fq=publishedOnDate:[Feb+29%2C+2016+TO+Mar+29%2C+2016]&fq=publishedOnDate:[Mar+29%2C+2016+TO+Apr+29%2C+2016]

**Comment by gsingers** [comment]
that's a good one, @arafalov!  Looking into it.

**Comment by gsingers** [comment]
This is a bug in Lucidworks View.  Will work to get it fixed.

**Comment by gsingers** [comment]
This is an issue in Lucidworks View.  A PR is available at https://github.com/lucidworks/lucidworks-view/pull/52.
